### PR TITLE
Update .gitignore to ignore personal data folders

### PR DESCRIPTION
**Pull request by namkyu1999**
## Description
docker-compose automatically generate db/data folder(for mariadb) and web-data folder(for web).
That folders are unreleated to project because They are personal data.
So add folders name to .gitignore
- Issue number #30 
## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
I want to add @riyenas0925 to reviewer.
But I can't add him to the reviewer... 

@riyenas0925 , 
Please leave your review as a comment.

**Comment by riyenas0925** [comment]
@soimkim 
Is there a convention for leaving a review?

**Comment by soimkim** [comment]
@riyenas0925 ,
There is no convention on reviews.
I asked you for a review because you discussed it in an issue #30.

**Comment by riyenas0925** [comment]
@soimkim 
Everything discussed in the issue is reflected in PR Thank you!

**Pull request merged**
