### PR TITLE
Convert comment data created by Check Oss Name into table format #945

### LINKED ISSUE #945: Change format of auto generated comment (Check License)
Comment is generated automatically when licenses are changed by **Check License**.
Change comment format as table like below.

**Check License**로 license이름이 바뀔때, comment가 자동 생성이 됩니다.
Comment를 아래와 같이 표 형식으로 변경하려 합니다.

- AS - IS : 
image

- TO - BE :

**The following Licenses were modified by "Check License"**

OSS Name | OSS Version | Download location | Before Change | After Change
-- | -- | -- | -- | --
AWS IoT Device SDK for Python | 1.4.9 | https://pypi.org/project/AWSIoTPythonSDK/1.4.9 | Apache Software License | Apache-2.0
aioboto3 | 8.0.5 | https://pypi.org/project/aioboto3/8.0.5 | Apache Software License | Apache-2.0
aiohttp | 3.6.2 | https://pypi.org/project/aiohttp/3.6.2 | Apache Software License | Apache-2.0

</body>
</html>

### PR DESCRIPTION
**Pull request by jiwon83**
## Description
closes #945 
Change comment history's content to table format when auto-creating comment history in check OSS license. 

## Solution
- Add html table Flag for meaning the last element in the comment list.
```
private String tableFlag ="N";
```
<br>

- Add html table tag in saveOssCheckLicense function of AutoFillOssInfoServiceImpl.java

<br>

- Add tableFlag data in the changeProc function in checkOssLicensepopup.jsp

```
rowdata["tableFlag"] = "N";
if( i == idArry.length -1 ){
    rowdata["tableFlag"] = "Y";
}
```
As Is :
image
<br>

To Be :
image
<br>

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by 70825 — CHANGES_REQUESTED** [review]
1. Combine all commits and DCO check again plz
2. [Turn off the wildcard setting in your import statement](https://velog.io/@eora21/Intellij%EC%97%90%EC%84%9C-%EC%99%80%EC%9D%BC%EB%93%9C%EC%B9%B4%EB%93%9C-%EC%9E%84%ED%8F%AC%ED%8A%B8-%EC%84%A4%EC%A0%95-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0)
3. Delete all `System.out`, `console.log`, [You can see the code you changed here](https://github.com/fosslight/fosslight/pull/961/files)

**Review by jongwooo — COMMENTED** [review]
1. In your local branch, run: `git rebase HEAD~4 --signoff`
2. Force push your changes to overwrite the branch: `git push --force-with-lease origin jiwon945`

**Comment by Youngseo-Jeon0313** [comment]
@jiwon83 
I think the error occurs because signed off is duplicated in [this commit](https://github.com/fosslight/fosslight/pull/961/commits/9692915a06cd382a1533116a875803cb3bcddf89)! I think you can use git squash to group it with [the last commit](https://github.com/fosslight/fosslight/pull/961/commits/6b4497c1a3f6701232a88904e2bcf00288f06ae6), and change the commit message appropriately within 50 characters, and force push it.

**Comment by jiwon83** [comment]
@Youngseo-Jeon0313 @jongwooo @70825 Thank you so much, I tried git rebase and squash to solve the DCO error. But I couldn't do that because of one of the commits. 
 So, I just made a new branch and applied the code necessary. I thought it was more safe way. I am not used to dealing with git rebase and force push.
 This is my new pull request #962

**Pull request closed without merging**
