### PR TITLE
Search website regardless of http://, https://, www.

### PR DESCRIPTION
**Pull request by doggai10**
Signed-off-by: doggai10 <doggai77@gmail.com>

## Description
modify OSS controller that allow users to search download location regardless of https://, http://, www

first check HttpServletRequest parameter homepage and convert url.
if homepage url starts with http:// or www, OSS search couldn't find OSS that has exact same download location.
so if homepage starts with http:// or www., convert url that starts with https:// and save homepage url using setHomepage function.

-test results
131239617-2ca85dde-944a-4355-9d6b-a1d472291647
131513346-0a025ae3-fd7c-49e8-9796-de9c6e6a69fc
131239620-250d2afe-5c09-4202-939c-a6ee47a74b73
131239618-812a8557-d4e1-4975-bc91-280ddc27573f

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
Dear @doggai10 ,
Sorry for the late review.


This patch has one bug.
It should also be possible to search only some characters included in external links.
ex) If only "pypa/packaging" is entered in the website, the OSS link, https://github.com/pypa/packaging, should be searched.

**Comment by doggai10** [comment]
Dear @soimkim ,
i fixed the bug that if some characters included in external links, it should be possible to search.

- screen shots
스크린샷 2021-09-09 오후 11 42 05
스크린샷 2021-09-09 오후 11 41 55

**Comment by soimkim** [comment]
Dear @doggai10 ,
This patch is intended to be searchable regardless of http:// https:// www.

However, this patch changes http:// and www to https://. For this reason, it is not possible to search for the case saved as http:// as shown in the following capture.
image


If it starts with http://, www., https://, how about deleting the (http://, www., https:// https://www. http://www.)?

**Comment by doggai10** [comment]
Dear @soimkim ,
i modified the logic the way that you mentioned earlier.
if url starts with http:// then delete http://
if url starts with http://www. then delete http://www.
if url starts with https:// then delete https://
if url starts with https://www. then delete https://www.

- screenshot
스크린샷 2021-09-10 오전 9 43 15
스크린샷 2021-09-10 오전 9 50 10

**Pull request merged**
