### PR TITLE
Add auto-updating CHANGELOG.md on develop branch

### PR DESCRIPTION
**Pull request by riyenas0925**
* Using the matrix function of Github actions, both develop and main branches will be applied automatically.

## Notice
* If you want to add a new branch Just add it to the matrix of github actions.
```
strategy:
  matrix:
    ref: [main, develop, other branches.....]
```

### Before
There is no changelog in main branch and develop branch yet.
스크린샷 2021-08-13 오후 3 13 06

#### Test Release
Released branch feature/issue-57 for testing.
스크린샷 2021-08-13 오후 3 15 08

#### workflow
스크린샷 2021-08-13 오후 3 18 16

#### after branch
changelog is committed to each branch.
스크린샷 2021-08-13 오후 3 19 33

#### after changelog.md
|main|develop|
|:--:|:--:|
|스크린샷 2021-08-13 오후 3 20 31|스크린샷 2021-08-13 오후 3 21 29|

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
@riyenas0925 ,
In this case, separate commits are added to develop and main. 
If I create a PR from the develop branch to main later, the ChangeLog commit seems to cause a conflict.

**Comment by riyenas0925** [comment]
@soimkim 
I didn't think about that part. 😭 
Considering what you said, we will find another way!

**Comment by riyenas0925** [comment]
@soimkim 
Changed commit message applied, Below are the main and development branch.

스크린샷 2021-08-17 오후 9 13 34

**Comment by soimkim** [comment]
@riyenas0925 , Awesome. 👍

**Pull request merged**
