### PR TITLE
Modify button for extraction not included in the area of the results for Statistics

### PR DESCRIPTION
**Pull request by dener8**
## Description
1. Refactor HTML structure for 'Statistics'
 : Modify 'export data to excel' button not included in 'Project related (Divisional Project)'.
2. Update padding in CSS styles for 'Statistics'
 : Spread between area for search, button for extracting data to excel and area of search results.
   - AS-IS
   image

   - TO-BE
   image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by dener8** [comment]
@jongwooo 
Thank you! I have modified the commit message. 🙂

**Review by jongwooo — APPROVED** [review]
@dener8 Thanks for your contribution.

**Comment by Gseungmin** [comment]
Commit message subject length should be less than 50 lines!

Commit message body length should be less than 72 lines!

check your subject, body

**Comment by jongwooo** [comment]
We hold this PR because we need to rebase the commit history.

**Comment by soimkim** [comment]
커밋 정리 후 Ready for review 클릭해주십시오

**Comment by Youngseo-Jeon0313** [comment]
다음 과정으로 해결할 수 있어요!

1. private repo에 있는 fork sync 버튼을 통해 remote repo develop branch에 있는 commit history와 동기화가 되어 같게 나열되는지 확인한다.
2. 이후 local git(로컬 컴퓨터)에서의 develop branch 를 origin develop(github private repo develop 브랜치)과 일치시킨다.
3. dener8:chore branch에서 git checkout -b temp-branch [해당 PR을 날리기 전 커밋 (1f3c72a) ] 으로 develop에서 새로운 커밋로그를 쌓는다.
4. force push

+추가적으로 cherry pick 방법도 있습니다!

**Pull request closed without merging**
