### PR TITLE
OSS > add > new icon for newly added nicknames

### PR DESCRIPTION
**Pull request by Lightieey**
## Description

Added nick icon for newly added nicknames.
(I used the nick icon because there was no new icon, so please check it.)
Screenshot 2023-07-30 at 2 26 09 PM
closed: #882 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by Lightieey** [comment]
> For me, it looks like the photo below. 스크린샷 2023-08-03 오후 10 01 14

@70825 
Can you show me the inspect tab like the picture below?
(please click the element nick icon and show the Styles tab together)
Screenshot 2023-08-03 at 10 31 07 PM

**Review by 70825 — COMMENTED** [review]
??
I tried running it again now and it works fine.
I'll check it periodically.

스크린샷 2023-08-04 오전 9 49 52

스크린샷 2023-08-04 오전 9 51 10

**Comment by Lightieey** [comment]
@70825 
Maybe it's because the css file has changed.
If the css file changes, you have to press cmd+shift+R to apply the changes.
I don't know if you already know, but I'm leaving a comment in case you didn't.
Thanks for checking!!

**Review by 70825 — APPROVED** [review]
> If the css file changes, you have to press cmd+shift+R to apply the changes.

 I didn't know that 😀 Thanks for the knowledge 👍

**Pull request merged**
