### PR TITLE
Auto upload identification invalid data to oss bulk registration

### PR DESCRIPTION
**Pull request by MoonDD99**
Signed-off-by: MoonDD99 <mjh991016@naver.com>

## Description
Auto upload unconfired version/oss data to oss bulk registeration pop up from project identification SRC and BIN

## Screenshot
- The screenshot that follows is oss bulk registration pop up from Project identification 
oss bulk registration 캡쳐

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by FRESH-TUNA — COMMENTED** [review]
Please merge into one commit.
Refactor commit is inappropriate in this PR.

**Comment by soimkim** [comment]
Dear @FRESH-TUNA, in this case I will squash and merge. 😉

**Comment by riyenas0925** [comment]
LGTM :+1:

**Comment by soimkim** [comment]
@MoonDD99 , Unconfirmed open source, Unconfirmed version만 OSS Bulk registration에 load되어야 합니다. 
- 사유 : 신규 OSS, 신규 버전을 등록하기 위한 기능이므로 등록되지 않은 OSS에 대해서만 load함.
- 수정이 필요한 사항 :  하기와 같이 Declared로 warning message 표시되는 경우에도 OSS Bulk 에 load됩니다. 
image

**Review by FRESH-TUNA — APPROVED** [review]
L.G.T.M !

**Pull request merged**
