### PR TITLE
Show a failed message in Self-check.

### PR DESCRIPTION
**Pull request by JoHyoju04**
## Description

This is the PR related to the button in the self-check tab of task7.

1. when you click the OSS Notice button before clicking the save button in Self-Check, show a failed message.

1-1. This is when you click the "notice" button first.
image

1-2. This is when you save button before clicking the OSS Notice button.
image
image

2. When you click the save button in Self-Check, show a check message for unconfirmed license.
2-1. there is unconfirmed license.
image

2-2. it’s all confirmed
image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by namkyu1999** [comment]
You have 7 commits incorrectly signed off. Check DCO please

**Comment by soimkim** [comment]
- When saving, the current operation should be maintained. (Can be saved regardless of warning message)
- When OSS Notice is issued, an error pop-up should be displayed when clicking the OSS Notice button to notify about unregistered licenses.
- It is difficult to determine whether a license is registered in the License List only with a warning message.

**Comment by soimkim** [comment]
#242 is what should be done first, so I change this PR to Draft first.

**Comment by soimkim** [comment]
image
Notice tab has been added in Self-check.
And a function that notifies user with a pop-up about licenses not registered has been implemented.

Therefore, I will close this issue.

**Pull request closed without merging**
