### PR TITLE
Enhancement function : Recommend the OSS Name according to the OSS Naming Rule

### PR DESCRIPTION
**Pull request by namkyu1999**
## Description

1. Now fosslight supports 6 open source package repositories (GitHub, Maven, PyPI, npm). To support two additional open source package repositories (Pub, CocoaPods), Modified fosslight_create.sql, OssServiceImpl::checkOssName, and OssServiceImpl::saveOssCheckName as follows.

2. And fosslight recommends an oss name by checking the oss list.
If the download location is not stored in the OSS List only for the OSS Name that is an Unconfirmed Open Source Warning message, recommend the OSS Name according to the OSS Naming Rule.

So in Project List > SRC tab, As shown in the picture below, Suppose that there is an open source specified in the downloadlocation for a specific repository and 'Unconfirmed Open Source' warning message is appeared.
image
If opensource's download location is specified in 6 open source package repositories (GitHub, Maven, PyPI, npm, Pub, CocoaPods), The oss name is automatically recommended by the oss naming rule, and the oss name can be replaced with this name.
image

- Issue number
-- #78 
-- #79 

## Type of change
Please insert 'x' one of the type of change.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by hyewoncc** [comment]
LGTM👍

**Comment by namkyu1999** [comment]
Dear @soimkim 
I've reflected everything you commented on.
Can you review again?

**Comment by soimkim** [comment]
Dear @namkyu1999 ,
1. The following OSS Name is not stored in the OSS List.
However, the warning message "Unconfirmed open source" does not appear in bear and alert. Could your modification have affected the display of the warning message?
image

2. If you look at the capture below, when I click "Add nickname", it loads infinitely. For reference, OSS Name to be changed is not saved in OSS List.
image

**Comment by namkyu1999** [comment]
Dear @soimkim ,
Solved the above issues.

**Comment by soimkim** [comment]
Dear @namkyu1999 ,
Is the merge commit added because of a code conflict?
How about removing the merge commit?

**Comment by namkyu1999** [comment]
Okay i will remove it

**Comment by namkyu1999** [comment]
Dear @soimkim 
What you said has been reflected.

**Comment by namkyu1999** [comment]
Dear @soimkim 
I reflected everything you said.

**Comment by wkdalsgh192** [comment]
LGTM 😎 Keep going hard!

**Comment by soimkim** [comment]
Dear @namkyu1999 ,
It works well. 👍
 
Let's merge the commits as follows.
image
I'll merge this PR after you merge the commit.

**Comment by namkyu1999** [comment]
Dear @soimkim 
Everything is reflected :)

**Pull request merged**
