### PR TITLE
Show a comment input window when the drop button is clicked

### PR DESCRIPTION
**Pull request by KosyAbone**
## Description

From Profile Basic Information Tab => 
Open the project => 
When the drop button is clicked, then an input box shows(only when there's no comment) just like the delete button.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by KosyAbone** [comment]
Hello @soimkim Kindly review my pull request. Thanks

**Comment by soimkim** [comment]
1. Let's change the pop-up message.
`Are you sure you want to drop this project? This will permanently drop all datas.` -> `Are you sure you want to drop this project?`
3. Even if I click drop after entering a comment in the comment edit window, a pop-up to receive comments appears.
image
- If I click drop after entering a comment in the comment edit window, a popup to receive comments should not appear.
4. The comments entered do not remain in the comment history after dropping.
AS-IS: 
image
image
It should be able to check what user entered in the comment input window when user clicks `Show comment history` after dropping.

**Comment by KosyAbone** [comment]
Alright. I'll work on implementing these modifications.

**Comment by KosyAbone** [comment]
I cant seem to find where i can click to open up the area for edit comment. Please help!


Screen Shot 2022-05-07 at 12 32 39 AM

**Comment by soimkim** [comment]
@KosyAbone , If you click the `Comment edit` button, you can see the comment input window.
For reference, if you click the `Show comment history` button to the left of the `Comment edit` button, you can check the list of comments left on the project.
image

**Pull request closed without merging**
