### PR TITLE
Added watcher search box in Project List, 3rd Party List

### PR DESCRIPTION
**Pull request by Youngseo-Jeon0313**
## Description
This PR add watcher feature to  **#817**

## AS-IS

There is no watcher box in search box.
Untitled (18)
Untitled (19)

## TO-BE

User can search watchers using search box

> Project part

https://github.com/fosslight/fosslight/assets/81344634/3abebd9f-4f6d-4889-b619-832da458c425

> Partner part

https://github.com/fosslight/fosslight/assets/81344634/1366148d-b7e9-4283-83cc-87978a5e27c9

> I added 3 data to show how _search_ works.

https://github.com/fosslight/fosslight/assets/81344634/de90a66f-ded0-4b93-be71-99c2f26394a6

### ProjectMapper.xml
When we search, we need to include the watcher and import all satisfied projects from the DB. To do so, a query statement was needed to import all the projects in question from the DB. Therefore, we added code to ProjectMapper.xml to import the query statement including the watcher item.

### searchConditionArea.jsp
I added watcher box here. We can get data from watcher input box when we press search button.

### project/list.jsp & project/list-js.jsp
we need to show "watcher input" on search box and "watcher row" on table below. So I placed the contents in the search box appropriately, and added watcher row.

The 3rd Party (Partner) part is also the same.

## Type of change

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Documentation update
- [ ]  Refactoring, Maintenance
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Comments

Hello! This is my first PR, and I improved my understanding of **mybatis** language and **this FOSSLIGHT project** through this opportunity. I thoroughly analyzed several codes for the watcher, and I think there may be several extensions of this issue(of this watcher part!!). In my next contribution, I want to try further contribution in relation to the watcher. 
Please refer me if you need further clarification or requirements!

### CODE REVIEW

**Review by 70825 — CHANGES_REQUESTED** [review]
1. Edit the PR title.
2. Please remove the commit between [ab2c00e](https://github.com/fosslight/fosslight/pull/934/commits/ab2c00ee205f5c483ccf740c3b186024a3647042) and [2884d31](https://github.com/fosslight/fosslight/pull/934/commits/2884d31ff5a518a0f90e359404eabb6e4397078c).
3. 1 data seems too meager to show results. Can you show an example with at least 2 data?

Please apply the above 3 points before i can review.

**Comment by Youngseo-Jeon0313** [comment]
I have one question for you! As you can see in the 3rd video, if I enter the 'Add' page and then return to the project List page, I can see garbage values ​​being written to the watchers input box. Do you know the reason for this? I just found out about this issue while filming a video, so I'll think about this a bit more! Thanks a lot! 🤗

**Comment by 70825** [comment]
@Youngseo-Jeon0313 
I would appreciate it if you could edit the video after modifying the code.
I will proceed with the code review next time

**Review by jongwooo — COMMENTED** [review]
@Youngseo-Jeon0313 Consider combining commits [0a78df5](https://github.com/fosslight/fosslight/pull/934/commits/0a78df56d07657ff16d9849a748bb1eacd125ce5) and [280359c](https://github.com/fosslight/fosslight/pull/934/commits/280359c035367869b33d8022c98420b681485d83) into one using squash.

**Review by 70825 — CHANGES_REQUESTED** [review]

**Review by 70825 — COMMENTED** [review]
1. 현재 이슈와 관련 없는 쿼리문에도 쿼리 수정을 하셨는데, Mapper 코드쪽만 각각 왜 코드 수정을 했는지 알려주시면 감사드리겠습니다.
2. 코드 리뷰를 할 때, indent가 지켜지지 않아서 코드 읽는데 어려움이 있습니다. [Files changed](https://github.com/fosslight/fosslight/pull/934/files)에 들어가주셔서 확인해주시고, 기존의 다른 코드와 똑같은 indent로 수정해주세요.

첫 기여인데 어려운 이슈 맡으셔서 고생 많으셨습니다 👍

**Comment by Youngseo-Jeon0313** [comment]
While checking the codes I had written in the xml file, I found the codes out of the current issue. The codes I wrote before were codes to show the watchers in the table below, not to search in the search box. So I deleted all those codes and sent PR again!

I will write a brief description of the current xml code. First, PROJECT_MASTER and PROJECT_WATCHER are joined by project_id. Afterwards, group all user_id or email in PROJECT_WATCHER with ‘,’ into one string. (For example, “*user, [oss@gmail.com](mailto:oss@gmail.com), [fosslight@naver.com](mailto:fosslight@naver.com)”*). Afterwards, if I search by entering data into the watcher input, a select query is executed to determine if there is a word corresponding to it.

**Comment by soimkim** [comment]
@Youngseo-Jeon0313 님, 결과 Table에서 Watcher column은 삭제 부탁드립니다.

**Pull request merged**
