### PR TITLE
Update newLogo in login, signup, menu bar

### PR DESCRIPTION
**Pull request by MoonDD99**
## Description

Update newLogo in login, singup, menu bar
#461 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
@MoonDD99 , please refer to the guide at https://fosslight.org/fosslight-guide/learn/1_contribution.html to see how to sign a DCO.

**Comment by soimkim** [comment]
And in src/main/resources/static/images, the logo file name should be img_logo.png, but it is renamed as img_log.png.

**Comment by MoonDD99** [comment]
@soimkim I solved it

**Comment by soimkim** [comment]
@MoonDD99 , please check the file name. 😃

**Comment by MoonDD99** [comment]
@soimkim I fixed the file name

**Comment by soimkim** [comment]
Dear @MoonDD99 , would you merge them into one commit?

**Comment by MoonDD99** [comment]
@soimkim 
Done, If there is another issue, Please send the comment :)

**Pull request merged**
