### PR TITLE
Created Dockerfile and docker-compose.yml

### PR DESCRIPTION
**Pull request by sameer1046**
## Description
Deployment in Docker-Compose

### CODE REVIEW

**Comment by sameer1046** [comment]
Waiting

**Comment by k2heart** [comment]
@sameer1046 I'm waiting for your contribution!

**Comment by soimkim** [comment]
Dear @sameer1046 ,
1. To make the license information clear, please edit the above comment as follows.
```
# Copyright (c) Sameer1046
# SPDX-License-Identifier: AGPL-3.0-only
```
2. Please add the --signoff option to git commit.
Refer to the link below.
- https://github.com/fosslight/fosslight/pull/3/checks?check_run_id=2795166953

**Review by sameer1046 — COMMENTED** [review]
Spdx identifier and label maintaner added

**Comment by soimkim** [comment]
Dear @sameer1046 ,

Your contribution is an essential feature of FOSSLight. 

When contributing later, when committing, it would be really appreciated if you could clarify that you agree to the [Developer Certificate of Origin (DCO)](https://github.com/fosslight/fosslight/blob/main/CONTRIBUTING.md#Developer-Certificate-of-Origin) through sign-off.

Thanks for your contribution.

**Pull request merged**
