### PR TITLE
Add a function to check details detected license.

### PR DESCRIPTION
**Pull request by ubermen5che**
## Description
-  issue: [Add ability to allow users to check Detected Licensing details. #44](https://github.com/fosslight/fosslight/issues/44)
-  Add a function to check details detected license
-  Add CSS for detected license text color

## Note
- The detected licenses added to OSS cairo during the test were arbitrarily added from the admin account.

## Before
ezgif com-gif-maker

## After
ezgif com-gif-maker (1)

**Code reviews are always welcome**
Thank you

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
You uploaded gif files!!! awesome!!! 👍

**Comment by soimkim** [comment]
Dear @ubermen5che ,
It is not reflected in demo.fosslight.org, so please check it again.

**Comment by soimkim** [comment]
@ubermen5che , 
In this function, only general users can click the link, but I was mistaken because I logged in as an admin. 
This function works fine. 👍

**Comment by ubermen5che** [comment]
Okay. So it's not the case that I have to re-edit the code, am I?

**Comment by soimkim** [comment]
@ubermen5che , yep. There is nothing to modify. :-)

**Pull request merged**
