### PR TITLE
Save language settings per user

### PR DESCRIPTION
**Pull request by riyenas0925**
## Description
Save language settings per user.
- Default value : en_US

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by riyenas0925** [comment]
DB change query

```sql
alter table T2_USERS
	add DEFAULT_LOCALE varchar(10) default 'en_US' null;
```

**Review by yugeeklab — COMMENTED** [review]
LGTM!

**Review by yugeeklab — APPROVED** [review]

**Comment by soimkim** [comment]
@riyenas0925 , 
fosslight_create.sql file needs to be updated.

**Comment by riyenas0925** [comment]
@riyenas0925 
I will change the fosslight_create.sql

**Pull request merged**
