### PR TITLE
In default state, add one declared license in new_opensource tab, Change to cotent of the email from License Name to License

### PR DESCRIPTION
**Pull request by chd830**
## Description
1. Change the default setting of declared license in oss list to the state where one license row is added.
2. Change to content of the email from 'License Name' to 'License' If edit OSS information.

### Before
image

### After
image

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
> Dear @chd830 ,
> In this case, if I click the OSS on OSS List where the license is already registered, one more license is added.
> image
> 
> It needs to be modified so that it is added only when the license is not registered.

@chd830 , 
The issue I left in the comments above has not been resolved. 
Please review and make further corrections.

**Comment by soimkim** [comment]
Dear @chd830 ,
It needs to be modified so that the empty row is added only when the license is not registered.
https://github.com/fosslight/fosslight/pull/84#issuecomment-907718360

**Review by soimkim — CHANGES_REQUESTED** [review]
Dear @chd830,
Please modify to add an empty row only when the row of license is not blank.
And let's merge the commits into one.

**Comment by soimkim** [comment]
@chd830 ,
image
- OSS List > Click Add > If you click Save after entering OSS name and license, an error occurs.

And please check the indentation in the code. You'll have to change Space to Tab.

**Comment by soimkim** [comment]
@namkyu1999 ,
Please review this PR.
If you test this PR, OSS cannot be saved. An error occurred when clicking Save in the new OSS creation tab. -> Please comment on this as well.

**Review by namkyu1999 — CHANGES_REQUESTED** [review]
An error occurred when clicking the save button

image

**Pull request closed without merging**
