### PR TITLE
Delete duplicate buttons in identifying a project

### PR DESCRIPTION
**Pull request by wkdalsgh192**
Signed-off-by: mhjang <mhjang@miridih.com>

## Description
This PR deletes duplicate buttons on the Identification page so that help developers not to be confused about what they do. Additionally, I changed the default height of the OSS table from '500px' to 'auto' so as to show the remaining buttons with no scrolling.

|TARGET| AS-IS | TO-BE |
| --- | --- | --- |
|Project List | image |When you have no scroll, a group of buttons lies on the OSS table. image If you scroll down to the bottom, it disappears and shows up below the table, and vice versa.  |
|3rd Party | image| image |
|SRC | image | image|
|BIN| image  | image |
|BOM| image | image|

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by wkdalsgh192** [comment]
This PR is linked to #138 . Please add the issue to the 'Linked Issues'.

**Comment by soimkim** [comment]
Dear @wkdalsgh192 ,
As a result of testing in the project list, I had to scroll to see the buttons.
The following capture is before scrolling, so the buttons are not visible.
image

**Comment by wkdalsgh192** [comment]
@soimkim Oh, I see. The buttons need to be above the table in the Project List. Do you think the others in the Identification page should be the same?

**Comment by soimkim** [comment]
@wkdalsgh192 , 
As written in the [issue](https://github.com/fosslight/fosslight/issues/138), the reason for the double placement of the buttons above and below the table is to make it easier to click the button even when it is scrolled. Because the list can be long. So, as you said in the [issue](https://github.com/fosslight/fosslight/issues/138), the buttons should be visible whether scrolling or not. And this needs to be applied equally to the project list, Identification, 3rd party list, 3rd party, and self-check.

**Comment by wkdalsgh192** [comment]
@soimkim I decided to make the buttons toggled when a user scrolls, comparing between two options that we've said earlier. This PR only updates the Project List for your test. The remaining pages will be changed once you confirm these changes. pls see the screenshot above. 😄

**Comment by soimkim** [comment]
Dear @wkdalsgh192 ,
Does the button at the bottom become visible when the user scrolls? 
Does the toggle mean that the buttons at the bottom will be hidden when the user scrolls up again?

**Comment by wkdalsgh192** [comment]
@soimkim it appears below the table when he or she scrolls down to the bottom and does above the table when the scroll reaches the top of the page.

**Comment by soimkim** [comment]
Dear @wkdalsgh192 ,
How about making the bottom button change to visible only when scrolling down?

**Pull request closed without merging**
