### PR TITLE
Remove unused import statements

### PR DESCRIPTION
**Pull request by D0ri123**
## Description

I removed unused import statements in src/main/java/oss/fosslight/config, controller
Then, I checked that project works well.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [X] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by jongwooo — CHANGES_REQUESTED** [review]
@D0ri123 Thanks for your contribution. Consider combining [2a011bd](https://github.com/fosslight/fosslight/pull/869/commits/2a011bd636aabf509ea236550c45f2056c513c5e) and [5748b4a](https://github.com/fosslight/fosslight/pull/869/commits/5748b4acf90ad08239e5b4f74d002c570fdbbd24), [6bca857](https://github.com/fosslight/fosslight/pull/869/commits/6bca857e082da654904696664f9c47af7078c970) into a single commit(e.g. `Remove unused import statements`) with squash.

**Review by jongwooo — APPROVED** [review]
@D0ri123 LGTM. Thanks!

**Comment by D0ri123** [comment]
Thanks for your kindly reviews😃, can I close my issue if this merge??

**Review by jongwooo — COMMENTED** [review]
@D0ri123 By adding the following to the pull request description, we can automatically close the issue when the pull request is merged:

```text
Closes #868 
```

See also https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Pull request merged**
