### PR TITLE
Fix a typo in the notice template

### PR DESCRIPTION
**Pull request by syleeeee**
## Description
There was a typo in text format of the notice template. 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by jongwooo — CHANGES_REQUESTED** [review]
@syleeeee Thank you for your contribution, but please sign the commit for DCO.

**Comment by syleeeee** [comment]
Does fixing one typo really need DCO?

**Comment by jongwooo** [comment]
We sometimes forget to add DCO too😅 However, we are trying to follow the guideline in CONTRIBUTING.md. Thank you!

**Comment by syleeeee** [comment]
Sorry to bother you, but what should I do now? I amend the commit and added a commit message for DCO. And I think it doesn't work.

**Comment by jongwooo** [comment]
> Commit sha: [97d03b0](https://github.com/fosslight/fosslight/pull/837/commits/97d03b01c855a879a7ef09257765a445220b1f75), Author: Seo-yeon Lee, Committer: syleeeee; Expected "Seo-yeon Lee [seo-yeon.lee@linecorp.com](mailto:seo-yeon.lee@linecorp.com)", but got "Seoyeon Lee [seo-yeon.lee@linecorp.com](mailto:seo-yeon.lee@linecorp.com)".

I found it in the logs of the DCO app, please refer to the logs above and fix it :)

**Comment by syleeeee** [comment]
Ah! It's done now. Thanks!

**Review by jongwooo — APPROVED** [review]

**Pull request merged**
