### PR TITLE
Run docker with sudo privileges

### PR DESCRIPTION
**Pull request by soimkim**
## Description
Run docker with sudo privileges.

## Type of change
Please insert 'x' one of the type of change.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
@riyenas0925 , @namkyu1999 ,
I tried to run docker without sudo, but it doesn't work without sudo because of the permissions of files created when docker was run before.
Finally.. I added sudo.

**Comment by riyenas0925** [comment]
@soimkim 

LGTM 😄 

a permission problem can be used without sudo by using the following command on the remote server.

```sh
sudo usermod -aG docker $USER
```

**Comment by soimkim** [comment]
@riyenas0925 ,
I ran docker without sudo with the command you left.
However, when I build and run it, the file created when docker was previously executed has root permission, so it fails.

**Comment by riyenas0925** [comment]
thank you, understood well :smile:

**Pull request merged**
