### PR TITLE
Add Line Separator Between Notice Intro And OSS Lists

### PR DESCRIPTION
**Pull request by wkdalsgh192**
Signed-off-by: mhjang <mhjang@miridih.com>

## Description
When you download an OSS Notice file in a .txt type, this adds a line separator between the notice introduction and the OSS list that will be packaged.

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by wkdalsgh192** [comment]
@soimkim Can you set the 'Linked issues' tag into #111? I think I should be able to do but currently, I can't.

**Comment by wkdalsgh192** [comment]
@soimkim By this commit, a notice.txt file will be shown like : 

image

Please review the PR.

**Comment by soimkim** [comment]
@wkdalsgh192 , I did not review this PR as it is a draft PR. 

Please change your PR's status when PR is ready for review.
- https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

**Comment by wkdalsgh192** [comment]
My bad 😥 . It's all set now!

**Comment by soimkim** [comment]
Dear @wkdalsgh192 , Please update description of the PR. 😄

**Comment by wkdalsgh192** [comment]
I'm totally dumb 😭. Let me know if there are other mistakes.

**Comment by soimkim** [comment]
@wkdalsgh192 , LGTM. 👍

**Pull request merged**
