### PR TITLE
Add License Link CheckBox

### PR DESCRIPTION
**Pull request by JangYeonji**
## Description

#587 
Create License Link check box 
under Configuration > Notice Setting > Notice Type

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
@JangYeonji ,
1. Check indentation.
2. Check the DCO. :https://github.com/fosslight/fosslight/pull/606/checks?check_run_id=7561806318
3. Please update the description of this PR.

**Comment by soimkim** [comment]
If your PR isn't ready yet, change it to **Draft**.
image

**Comment by riyenas0925** [comment]
@JangYeonji 
Please refer to the link below to add your DCO sign
https://github.com/fosslight/fosslight/pull/606/checks?check_run_id=7561806318

**Review by jongwooo — COMMENTED** [review]
@JangYeonji ,

`Sign-off` is a line at the end of the commit message which certifies who is the author of the commit. Its main purpose is to improve tracking of who did what, especially with patches.

Example commit:

```
git commit -s -m "Update workflows to cache dependencies"
```

Result:

```diff
Update workflows to cache dependencies
+Signed-off-by: jongwooo <han980817@gmail.com>
```

If you have already done PR **without Sign-off**, please follow the command below.

```
git commit --amend --no-edit --signoff
git push -f
```

**Comment by soimkim** [comment]
@JangYeonji , Plz check the reviewer's comment.

**Pull request closed without merging**
