### PR TITLE
Add User Guide and Restriction to license popup

### PR DESCRIPTION
**Pull request by riyenas0925**
## Description
* add description column to jqgrid (hidden:true)
* add User Guide and Restriction to license popup
* if there are no restrictions, user guide, or license text, it will not be displayed. 

|before|after(all)|
|:--:|:--:|
|image|스크린샷 2021-09-15 오후 4 47 57|

|after(no restriction)|after(no user guide)|
|:--:|:--:|
|스크린샷 2021-09-15 오후 4 47 31|스크린샷 2021-09-15 오후 4 48 19|

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
Dear @riyenas0925 , How about adding the title in bold?
- User Guide
- Restrictions
- License text

**Comment by riyenas0925** [comment]
Dear @soimkim 

LGTM 👍 

I changed it as below.
스크린샷 2021-09-15 오후 4 18 14

**Comment by soimkim** [comment]
@riyenas0925 , Is it possible to not print at all if there is no restriction?

**Comment by soimkim** [comment]
Is it better to print the title even if nothing is printed? 
what do you think?

**Comment by riyenas0925** [comment]
@soimkim 
If there is no content, it seems better to me not to show it :+1: 
I'll fix it and commit it again!

**Comment by riyenas0925** [comment]
Dear @soimkim 

Edited as follows!

|all|no restriction|no user guide|
|:--:|:--:|:--:|
|스크린샷 2021-09-15 오후 4 47 57|스크린샷 2021-09-15 오후 4 47 31|스크린샷 2021-09-15 오후 4 48 19|

**Comment by wkdalsgh192** [comment]
LGTM 👍

**Comment by soimkim** [comment]
Dear @riyenas0925 , Please update the PR description to the final revision.

**Comment by riyenas0925** [comment]
Dear @soimkim 

Changed commit message, Thanks for the feedback 😄 

```
Add User Guide and Restriction to license popup 

* add description column to jqgrid (hidden:true)
* add User Guide and Restriction to license popup
* if there are no restrictions, user guide, or license text, it will not be displayed.

Signed-off-by: riyenas0925 <riyenas0925@gmail.com>
```

**Comment by soimkim** [comment]
@riyenas0925 , Oh, there was a communication misunderstanding. It is not a Commit message, but a request to update the PR description. 😄

**Comment by riyenas0925** [comment]
Dear @soimkim oh, I misunderstood 😅 
Changed the pr message.

**Pull request merged**
