### PR TITLE
Initialize test code setting

### PR DESCRIPTION
**Pull request by astrod**
Signed-off-by: jongun.chae <cha452jg@gmail.com>

## Description
Initialize test code setting with Junit 5. Also, I made test code for creating a project. 
Firstly, create a project. Then, read it using other API to check whether it correctly create or not.

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
Dear @astrod ,
Please review the build failed.
And in the PR description, please leave a description of what this PR is. 😃 
Because users who are not members of the FOSSLight development do not know what Task 1 is.

**Comment by astrod** [comment]
Thank you for your advice, @soimkim . I change description correctly. 
It seems to me that build fail occured because of gardle version. I guess that 4.7 might have a issue and it can be solved by upgrading it to 5.x.

I tested it to gradle wrapper and it worked since it is 6.8.2. But, I had same error when I tested it in 4.7. So, I think that we need to decide to change gradle wrapper version to 4.7, or upgrade gradle version in github action.

I saw it([link](https://stackoverflow.com/questions/57329362/error-could-not-find-method-platform-for-arguments-react-native-firebase)) and tell me if I misunderstand. 

Thatnks

**Comment by soimkim** [comment]
@astrod ,
If we upgrade the gradle version, won't other derivative issues occur?
The github action builds as defined in the Dockerfile. Are you saying that we need to update the gradle version in [Dockerfile](https://github.com/fosslight/fosslight/blob/develop/Dockerfile)?

**Comment by astrod** [comment]
I think that the version of gradle is 4.7.0 in dockerfile and it is different from the version of gradle wrapper. It might be a good idea to syncronize two version. 
I'm not sure there is any side effect of the version upgradle. [The upgrade document](https://docs.gradle.org/current/userguide/upgrading_version_4.html) might be helpful.

**Comment by soimkim** [comment]
Dear @astrod ,
Please add a commit that upgrades the gradle wrapper and gralde version to this PR.

**Comment by astrod** [comment]
I chagne a gradle version to 6.8.2 in dockerfile.

**Pull request merged**
