### PR TITLE
Add send to everyone when sending comments

### PR DESCRIPTION
**Pull request by riyenas0925**
## Description
* before : When saving comments, a window appears to select the destination to send mail, and you send mail to the selected target.
* after : When saving comments, set the sending target to all and send an email when saving comments

### before
GIF 2021-10-07 오후 10-42-23

### after
GIF 2021-10-07 오후 10-39-59

### alert message
image

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
@riyenas0925 ,
Sorry for the late review. Please resolve the conflict.

**Comment by riyenas0925** [comment]
@soimkim 
conflict resolved 😄

**Comment by riyenas0925** [comment]
@soimkim 
I reflected it 👍

**Comment by soimkim** [comment]
@riyenas0925 , This feature should be reflected when leaving a comment in all tabs.
Requires reflection in Packaging and 3rd Party.

**Pull request merged**
