### PR TITLE
Delete spdx-tools jar file and add spdx tools java dependency

### PR DESCRIPTION
**Pull request by riyenas0925**
## Description
* before : Convert spdx files using spdx-tools jar in cmd
* after : 
     1. Add the spdx tools java dependency and convert the file using the SpdxConverter method
        * version used org.spdx:tools-java 1.0.2 (15-Jul-2021 release)
        * mavencentral : https://search.maven.org/artifact/org.spdx/tools-java/1.0.2/jar
        * github release : https://github.com/spdx/tools-java
     2. Change null value in Package information sheet of SDPX (spreadsheet)
        * Download location : NONE
        * Copyright : NOASSERTION

GIF 2021-10-01 오전 2-19-13

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
@riyenas0925 ,
An error occurs when issuing an OSS Notice (SPDX RDF) including OSS for which the download location is null.
image

Error message:
```
web_1   | INFO  21-10-01 09:25:52[http-nio-8180-exec-2] [o.f.c.VerificationController:77] - URI: /project/verification/6
web_1   | ERROR 21-10-01 09:26:05[http-nio-8180-exec-10] [o.s.spreadsheetstore.SpdxSpreadsheet:137] - Required cell Package Download Location missing for row 1 in PackageInfo sheet.
web_1   | ERROR 21-10-01 09:26:05[http-nio-8180-exec-10] [o.f.c.SPDXDownloadController:162] - Error converting SPDX file: class org.spdx.spreadsheetstore.SpreadsheetException Required cell Package Download Location missing for row 1 in PackageInfo sheet.
web_1   | org.spdx.tools.SpdxConverterException: Error converting SPDX file: class org.spdx.spreadsheetstore.SpreadsheetException Required cell Package Download Location missing for row 1 in PackageInfo sheet.
web_1   | 	at org.spdx.tools.SpdxConverter.convert(SpdxConverter.java:178)
web_1   | 	at org.spdx.tools.SpdxConverter.convert(SpdxConverter.java:124)
web_1   | 	at oss.fosslight.util.SPDXUtil2.spreadsheetToRDF(SPDXUtil2.java:24)
web_1   | 	at oss.fosslight.controller.SPDXDownloadController.getExcelPost(SPDXDownloadController.java:87)
web_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
web_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
web_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
web_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
web_1   | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
web_1   | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
web_1   | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
web_1   | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
web_1   | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
web_1   | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
web_1   | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
web_1   | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
web_1   | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
web_1   | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
web_1   | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
web_1   | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
web_1   | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
web_1   | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
web_1   | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
web_1   | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
web_1   | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
web_1   | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
web_1   | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
web_1   | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
web_1   | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
web_1   | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
web_1   | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
web_1   | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
web_1   | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
web_1   | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
web_1   | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
web_1   | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
web_1   | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
web_1   | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
web_1   | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
web_1   | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
web_1   | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
web_1   | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
web_1   | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
web_1   | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
web_1   | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
web_1   | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
web_1   | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
web_1   | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
web_1   | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
web_1   | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
web_1   | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
web_1   | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
web_1   | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
web_1   | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
web_1   | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
web_1   | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
web_1   | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
web_1   | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
web_1   | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
web_1   | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
web_1   | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
web_1   | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
web_1   | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
web_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
web_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
web_1   | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
web_1   | 	at java.lang.Thread.run(Thread.java:748)
web_1   | Caused by: org.spdx.spreadsheetstore.SpreadsheetException: Required cell Package Download Location missing for row 1 in PackageInfo sheet.
web_1   | 	at org.spdx.spreadsheetstore.SpdxSpreadsheet.<init>(SpdxSpreadsheet.java:138)
web_1   | 	at org.spdx.spreadsheetstore.SpreadsheetStore.deSerialize(SpreadsheetStore.java:339)
web_1   | 	at org.spdx.tools.SpdxConverter.convert(SpdxConverter.java:151)
web_1   | 	... 77 common frames omitted

```

**Comment by riyenas0925** [comment]
@soimkim 
Can you send me the SPDX spreadsheet with the oss where the downloadlocation is null? I would like to run a test.

**Comment by soimkim** [comment]
SPDX Spreadsheet
[SPDXRdf-test_20211001.xls](https://github.com/fosslight/fosslight/files/7263417/SPDXRdf-test_20211001.xls)

**Comment by riyenas0925** [comment]
@soimkim 
The same error occurs in java online tools. Was it okay if the downloadLocation was null in the existing method?

image

**Comment by soimkim** [comment]
In the previously used jar file spdx-tools-2.2.2-jar-with-dependencies.jar, it worked even if it was null. It seems that the latest version of SPDX tool caused an error. If it is null, I need to check the SPDX Specification to see what to input.

**Comment by soimkim** [comment]
According to https://spdx.github.io/spdx-spec/package-information/, if it is null, it seems that output is required as NONE instead of blank. I'll look into it a bit more and comment.

**Comment by riyenas0925** [comment]
@soimkim 

SPDX Specifications
image

SPDX Github test xls
[SPDXSpreadsheetExample-v2.2.xls](https://github.com/fosslight/fosslight/files/7263498/SPDXSpreadsheetExample-v2.2.xls)
image

**Comment by soimkim** [comment]
Please check the spdx specification version that spdx-tool used before and the spdx specification version used by spdx-tool in this PR. 
In addition to the download location, it is necessary to review whether there is anything to correct the value.

**Comment by riyenas0925** [comment]
The test for NONE and NOASSERTION is missing, so I think it changed later.

Previous version : https://github.com/spdx/tools/releases/tag/v2.2.2 (26 Jul 2020)
test excel file
image

Current version : https://github.com/spdx/tools-java/releases/tag/v1.0.2 (15 Jul 2021)
test excel file
image


> The spdx-tools version is the legacy version and is currently recommended to use spdx-java-tools.

**Comment by riyenas0925** [comment]
@soimkim 
the column below is required 😄 
```
Package Name
SPDX Identifier
Package Download Location
License Declared
License Concluded
Package Copyright Text
```

### reference (PackageInfoSheetV2d2.java)
image

**Comment by riyenas0925** [comment]
for the definition of NONE and NOASSERTION,  refer to the comments below.
https://github.com/spdx/spdx-spec/issues/49#issuecomment-370161019

**Comment by soimkim** [comment]
When I try to download SPDX (RDF), it shows below warning messages.
``` 
web_1   | WARN  21-10-05 11:07:51[http-nio-8180-exec-8] [o.s.s.RdfSpdxDocumentModelManager:326] - Possibly ambiguous ID being introduced.  SPDXRef-Package-8 is being raplaced by SPDXRef-Package-8
web_1   | WARN  21-10-05 11:07:51[http-nio-8180-exec-8] [o.s.s.RdfSpdxDocumentModelManager:326] - Possibly ambiguous ID being introduced.  SPDXRef-DOCUMENT is being raplaced by SPDXRef-DOCUMENT
```

[SPDXRdf-testtest-eeee_20211005.xls](https://github.com/fosslight/fosslight/files/7282294/SPDXRdf-testtest-eeee_20211005.xls)

**Comment by riyenas0925** [comment]
@soimkim 
even if the id value and the previous value are the same, a warning message is displayed, so I asked if the function was intended.

화면 캡처 2021-10-05 122437

issue : https://github.com/spdx/spdx-java-rdf-store/issues/22

**Comment by soimkim** [comment]
The warning, `Possibly ambiguous ID being introduced`, also occurs in previous spdx tools, so fix it in another PR.

**Pull request merged**
